@startuml 自動販売機
[*] -right->入金待ち : 電源ON
state 入金待ち{
}
state ボタン選択待ち{
}
state ドリンク届け中{
}

入金待ち -down-> ボタン選択待ち : 料金を投入する

ボタン選択待ち -right-> ドリンク排出中 : ボタンを押す

ドリンク届け中 -up-> 入金待ち : ドリンクのお届け完了
入金待ち -right-> [*] : 電源OFF
@enduml