@startuml 製品製造
|営業部門|
start
:発注;
|販売代理店|
:受注;
:在庫の確認;
if () then (在庫なし)
    :;
    note right
    ダミーの
    アクティビティ
    を記述
    endnote
|製造部門|    
else (在庫あり) 
    :製造;
endif 
|販売代理店| 
:発注; 
|営業部門|
:検収/支払い;
|販売代理店|
:入金確認;
stop
@enduml